/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.plc4x.app.services.view;

import org.apache.plc4x.app.services.model.Plc4xDeviceNode;
import org.apache.plc4x.app.services.model.Plc4xDriverNode;
import java.beans.IntrospectionException;
import java.io.IOException;
import java.util.UUID;
import javax.swing.JDialog;
import javax.swing.JFrame;
import org.apache.plc4x.app.api.MasterDB;
import org.apache.plc4x.app.api.Plc4xDialog;
import org.apache.plc4x.app.api.Plc4xPropertyEnum;
import org.apache.plc4x.app.services.impl.DeviceRecordImpl;
import org.openide.cookies.InstanceCookie;
import org.openide.nodes.Node;
import org.openide.util.Exceptions;
import org.openide.util.Lookup;
import org.openide.util.lookup.Lookups;
import org.openide.util.lookup.ServiceProvider;
import org.apache.plc4x.app.api.DeviceRecord;
import org.apache.plc4x.app.api.DriverRecord;

@ServiceProvider(service=Plc4xDialog.class, path="Plc4xDriver/tag")
public class Plc4xAddTagDialog extends javax.swing.JDialog implements Plc4xDialog {

    private Plc4xPropertyEnum parameters;
    private final JFrame myJframe = new javax.swing.JFrame();
    private final MasterDB db = Lookup.getDefault().lookup(MasterDB.class);    
    Plc4xDriverNode drivernode;
    Node[] devicenodes  = new Plc4xDeviceNode[1];
     
    
    public Plc4xAddTagDialog() {
        super(new javax.swing.JFrame(), true);
        initComponents();

        DeviceRecord device = new DeviceRecordImpl();
        device.setUUID(UUID.randomUUID());
        try {
            devicenodes[0] = new Plc4xDeviceNode(device);
        } catch (IntrospectionException ex) {
            Exceptions.printStackTrace(ex);
        }           
    }

    /**
     * Creates new form NewJDialog
     */
    public Plc4xAddTagDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfDeviceProtocol = new javax.swing.JTextField();
        tfDeviceName = new javax.swing.JTextField();
        tfDeviceDesc = new javax.swing.JTextField();
        tfUUID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbEnable = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        btComms = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.title")); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.jPanel2.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.jLabel1.text")); // NOI18N
        jLabel1.setToolTipText(org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.jLabel1.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.jLabel2.text")); // NOI18N
        jLabel2.setToolTipText(org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.jLabel2.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.jLabel3.text")); // NOI18N
        jLabel3.setToolTipText(org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.jLabel3.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.jLabel4.text")); // NOI18N

        tfDeviceProtocol.setEditable(false);
        tfDeviceProtocol.setText(org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.tfDeviceProtocol.text")); // NOI18N

        tfDeviceName.setText(org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.tfDeviceName.text")); // NOI18N

        tfDeviceDesc.setText(org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.tfDeviceDesc.text")); // NOI18N

        tfUUID.setEditable(false);
        tfUUID.setText(org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.tfUUID.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(cbEnable, org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.cbEnable.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.jLabel8.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox1, org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.jCheckBox1.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDeviceProtocol, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDeviceName, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbEnable)
                                .addComponent(tfDeviceDesc)
                                .addComponent(tfUUID)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfDeviceProtocol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfDeviceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfDeviceDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfUUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbEnable))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jCheckBox1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btOk.setLabel(org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.btOk.label")); // NOI18N
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btCancel.setLabel(org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.btCancel.label")); // NOI18N
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btComms, org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.btComms.text_1")); // NOI18N
        btComms.setToolTipText(org.openide.util.NbBundle.getMessage(Plc4xAddTagDialog.class, "Plc4xAddTagDialog.btComms.toolTipText")); // NOI18N
        btComms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCommsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btComms)
                .addGap(89, 89, 89)
                .addComponent(btCancel)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOk)
                    .addComponent(btCancel)
                    .addComponent(btComms))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        this.setVisible(false);       
    }//GEN-LAST:event_btCancelActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        // TODO add your handling code here:
        devicenodes[0].setDisplayName(tfDeviceName.getText());
        
        //Everything's okay? Then we attach it to the database and to the representation on the screen
        final Plc4xDeviceNode beannode = (Plc4xDeviceNode) devicenodes[0];
        
        final InstanceCookie cookie = devicenodes[0].getLookup().lookup(InstanceCookie.class);

        try {

            final DeviceRecord dbr = (DeviceRecord) cookie.instanceCreate();
            dbr.setDeviceName(tfDeviceName.getText());
            dbr.setDeviceDescription(tfDeviceDesc.getText());
            //dbr.setUUID(uuid);
            //dbr.setTreeLocation(treenode);

            dbr.setPropertie(parameters.SERIAL_PORT.name(), (String) devicenodes[0].getValue(parameters.SERIAL_PORT.name()));
            dbr.setPropertie(parameters.BAUD_RATE.name(),   (String) devicenodes[0].getValue(parameters.BAUD_RATE.name()));
            dbr.setPropertie(parameters.DATA_BITS.name(),   (String) devicenodes[0].getValue(parameters.DATA_BITS.name()));   
            dbr.setPropertie(parameters.PARITY.name(),      (String) devicenodes[0].getValue(parameters.PARITY.name()));  
            dbr.setPropertie(parameters.STOP_BITS.name(),   (String) devicenodes[0].getValue(parameters.STOP_BITS.name()));              
            dbr.setPropertie(parameters.TIMEOUT.name(),     (String) devicenodes[0].getValue(parameters.TIMEOUT.name())); 

            
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        } catch (ClassNotFoundException ex) {
            Exceptions.printStackTrace(ex);
        }

        drivernode.getChildren().add(devicenodes);
    }//GEN-LAST:event_btOkActionPerformed

    private void btCommsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCommsActionPerformed
        // TODO add your handling code here:
        Lookup lk = Lookups.forPath("Plc4xDriver/" + drivernode.getDriverRecord().getProtocolCode());
        if ( lk != null) {
            JDialog dialog = lk.lookup(JDialog.class);
            ((Plc4xDialog) dialog).setNode(devicenodes[0]);
            dialog.setVisible(true);
        }        
    }//GEN-LAST:event_btCommsActionPerformed

    @Override
    public void setNode(Node node) {
        if (node instanceof Plc4xDriverNode) {
            this.drivernode = (Plc4xDriverNode) node;
            tfDeviceProtocol.setText(drivernode.getDriverRecord().getProtocolCode());
        } else
            System.out.println("Asignado tipo erroneo");
    }    

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b); 
        if (b) {
            
            //Crea nueva instanci o se debe reiniciar todos los parametros;
            final DriverRecord driver = db.getDriverByCode(drivernode.getDriverRecord().getProtocolCode());
            DeviceRecord device = new DeviceRecordImpl();
            try {
                devicenodes[0] = new Plc4xDeviceNode(device);
            } catch (IntrospectionException ex) {
                Exceptions.printStackTrace(ex);
            }            
        } else {
            devicenodes[0] = null;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plc4xAddTagDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plc4xAddTagDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plc4xAddTagDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plc4xAddTagDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Plc4xAddTagDialog dialog = new Plc4xAddTagDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btComms;
    private javax.swing.JButton btOk;
    private javax.swing.JCheckBox cbEnable;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfDeviceDesc;
    private javax.swing.JTextField tfDeviceName;
    private javax.swing.JTextField tfDeviceProtocol;
    private javax.swing.JTextField tfUUID;
    // End of variables declaration//GEN-END:variables


}
